# Base image for container
FROM node:20.12.0-alpine3.19


WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json  ./

COPY apps ./apps

COPY packages ./packages

# Install dependencies
RUN npm install

# Generate the prisma client
RUN npm run db:generate

# Build the app
RUN npm run build

# command to start the app
CMD ["npm", "run", "start-clientApp"]