FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json ./

COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN npm install

# Run the build command for production
RUN npm run build

# Generate the database
RUN npm run db:generate

# Start the production server
CMD ["npm", "run", "start-clientApp"]
